# .air.toml
[build]
cmd = "go build -o main ."
bin = "main"
include_ext = ["go"]
exclude_dir = ["vendor"]
delay = 1000
stop_on_error = true

[log]
time = true

[color]
main = "yellow"
watcher = "cyan"
build = "green"
runner = "magenta"
